spring.application.name=projectmanager

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8888

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

jwt-secret-key=${JWT_SECRET_KEY}
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}

kakao-redirect-uri=${KAKAO_REDIRECT_URI}